import {
  Backend,
  Devops,
  Frontend,
  Programming,
  Testing,
  Tools,
} from "@base/enum";
import type { Skill } from "@base/type";
import { IcSrcCode, IcReact, IcGlobe } from "@assets/icons";
import type { TFunction } from "i18next";

export const FrontendSkills = (t: TFunction): Skill[] => [
  {
    id: Frontend.React,
    title: t("react"),
    experience: 7,
    rating: 4,
    icon: IcReact,
  },
  {
    id: Frontend.ReactNative,
    title: t("reactNative"),
    experience: 2,
    rating: 4,
    icon: IcReact,
  },
  {
    id: Frontend.ReactRouter,
    title: t("reactRouter"),
    experience: 5,
    rating: 4,
    icon: IcReact,
  },
  {
    id: Frontend.ReduxToolkit,
    title: t("reduxToolkit"),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.ReduxSaga,
    title: t("reduxSaga"),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.RTKQuery,
    title: t("rtkQuery"),
    experience: 5,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Frontend.TanstackQuery,
    title: t("tanstackQuery"),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.MicroFrontend,
    title: t("microfrontend"),
    experience: 2,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Frontend.I18N,
    title: t("i18n"),
    experience: 5,
    rating: 4,
    icon: IcGlobe,
  },
  {
    id: Frontend.Formik,
    title: t("formik"),
    experience: 5,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Frontend.ReactHookForm,
    title: t("reactHookForm"),
    experience: 3,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Frontend.Zod,
    title: t("zod"),
    experience: 3,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.Yup,
    title: t("yup"),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.Joi,
    title: t("joi"),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.Axios,
    title: t("axios"),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.Mantine,
    title: t("mantine"),
    experience: 1,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Frontend.MaterialUI,
    title: t("materialUI"),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
];

export const BackendSkills = (t: TFunction) => [
  {
    id: Backend.Node,
    title: t("node"),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Backend.Express,
    title: t("express"),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Backend.MongoDB,
    title: t("mongoDB"),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Backend.Mongoose,
    title: t("mongoose"),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Backend.MySQL,
    title: t("mySQL"),
    experience: 5,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Backend.Firebase,
    title: t("firebase"),
    experience: 3,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Backend.Bun,
    title: t("bun"),
    experience: 1,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Backend.Elysia,
    title: t("elysia"),
    experience: 1,
    rating: 2,
    icon: IcSrcCode,
  },
];

export const ProgrammingSkills = (t: TFunction) => [
  {
    id: Programming.Typescript,
    title: t("typescript"),
    experience: 7,
    rating: 5,
    icon: IcSrcCode,
  },
  {
    id: Programming.JavaScript,
    title: t("javascript"),
    experience: 8,
    rating: 5,
    icon: IcSrcCode,
  },
  {
    id: Programming.HTML,
    title: t("html"),
    experience: 8,
    rating: 5,
    icon: IcSrcCode,
  },
  {
    id: Programming.CSS,
    title: t("css"),
    experience: 8,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Programming.SCSS,
    title: t("scss"),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Programming.SQL,
    title: t("sql"),
    experience: 5,
    rating: 3,
    icon: IcSrcCode,
  },
];

export const ToolsSkills = (t: TFunction) => [
  {
    id: Tools.GithubCopilot,
    title: t("githubCopilot"),
    experience: 1,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Tools.Vite,
    title: t("vite"),
    experience: 4,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Tools.ESBuild,
    title: t("esbuild"),
    experience: 1,
    rating: 2,
    icon: IcSrcCode,
  },
  {
    id: Tools.Webpack,
    title: t("webpack"),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Tools.Lighthouse,
    title: t("lighthouse"),
    experience: 4,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Tools.NewRelic,
    title: t("newRelic"),
    experience: 2,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Tools.Sentry,
    title: t("sentry"),
    experience: 2,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Tools.LogRocket,
    title: t("logrocket"),
    experience: 1,
    rating: 2,
    icon: IcSrcCode,
  },
  {
    id: Tools.WebpageTest,
    title: t("webpagetest"),
    experience: 3,
    rating: 4,
    icon: IcSrcCode,
  },
];

export const DevopsSkills = (t: TFunction) => [
  {
    id: Devops.Git,
    title: t("git"),
    experience: 7,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Devops.Github,
    title: t("github"),
    experience: 7,
    rating: 5,
    icon: IcSrcCode,
  },
  {
    id: Devops.AzureDevops,
    title: t("azureDevops"),
    experience: 5,
    rating: 5,
    icon: IcSrcCode,
  },
  {
    id: Devops.BitBucket,
    title: t("bitbucket"),
    experience: 3,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Devops.GithubActions,
    title: t("githubActions"),
    experience: 2,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Devops.Jenkins,
    title: t("jenkins"),
    experience: 8,
    rating: 2,
    icon: IcSrcCode,
  },
  {
    id: Devops.YAML,
    title: t("yaml"),
    experience: 2,
    rating: 3,
    icon: IcSrcCode,
  },
];

export const TestingSkills = (t: TFunction) => [
  {
    id: Testing.ReactTestingLibrary,
    title: t("rtl"),
    experience: 3,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Testing.Jest,
    title: t("jest"),
    experience: 7,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Testing.ReactTestingLibrary,
    title: t("vitest"),
    experience: 2,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Testing.Axe,
    title: t("axe"),
    experience: 3,
    rating: 3,
    icon: IcSrcCode,
  },
];

export const AllSkills = (t: TFunction) => [
  ...ProgrammingSkills(t),
  ...FrontendSkills(t),
  ...BackendSkills(t),
  ...ToolsSkills(t),
  ...DevopsSkills(t),
  ...TestingSkills(t),
];
