import {
  Backend,
  Devops,
  Frontend,
  Programming,
  Testing,
  Tools,
} from "@base/enum";
import type { Skill } from "@base/type";
import { IcSrcCode, IcReact, IcGlobe } from "@assets/icons";
import type { TFunction } from "i18next";

export const FrontendSkills = (t: TFunction): Skill[] => [
  {
    id: Frontend.React,
    title: t(Frontend.React),
    experience: 7,
    rating: 4,
    icon: IcReact,
  },
  {
    id: Frontend.ReactNative,
    title: t(Frontend.ReactNative),
    experience: 2,
    rating: 4,
    icon: IcReact,
  },
  {
    id: Frontend.ReactRouter,
    title: t(Frontend.ReactRouter),
    experience: 5,
    rating: 4,
    icon: IcReact,
  },
  {
    id: Frontend.ReduxToolkit,
    title: t(Frontend.ReduxToolkit),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.ReduxSaga,
    title: t(Frontend.ReduxSaga),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.RTKQuery,
    title: t(Frontend.RTKQuery),
    experience: 5,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Frontend.TanstackQuery,
    title: t(Frontend.TanstackQuery),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.MicroFrontend,
    title: t(Frontend.MicroFrontend),
    experience: 2,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Frontend.I18N,
    title: t(Frontend.I18N),
    experience: 5,
    rating: 4,
    icon: IcGlobe,
  },
  {
    id: Frontend.Formik,
    title: t(Frontend.Formik),
    experience: 5,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Frontend.ReactHookForm,
    title: t(Frontend.ReactHookForm),
    experience: 3,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Frontend.Zod,
    title: t(Frontend.Zod),
    experience: 3,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.Yup,
    title: t(Frontend.Yup),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.Joi,
    title: t(Frontend.Joi),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.Axios,
    title: t(Frontend.Axios),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.RadixUI,
    title: t(Frontend.RadixUI),
    experience: 1,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Frontend.Mantine,
    title: t(Frontend.Mantine),
    experience: 1,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Frontend.Shadcn,
    title: t(Frontend.Shadcn),
    experience: 1,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Frontend.MaterialUI,
    title: t(Frontend.MaterialUI),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
];

export const BackendSkills = (t: TFunction) => [
  {
    id: Backend.Node,
    title: t(Backend.Node),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Backend.Express,
    title: t(Backend.Express),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Backend.MongoDB,
    title: t(Backend.MongoDB),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Backend.Mongoose,
    title: t(Backend.Mongoose),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Backend.MySQL,
    title: t(Backend.MySQL),
    experience: 5,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Backend.Firebase,
    title: t(Backend.Firebase),
    experience: 3,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Backend.Bun,
    title: t(Backend.Bun),
    experience: 1,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Backend.Elysia,
    title: t(Backend.Elysia),
    experience: 1,
    rating: 2,
    icon: IcSrcCode,
  },
];

export const ProgrammingSkills = (t: TFunction) => [
  {
    id: Programming.Typescript,
    title: t(Programming.Typescript),
    experience: 7,
    rating: 5,
    icon: IcSrcCode,
  },
  {
    id: Programming.JavaScript,
    title: t(Programming.JavaScript),
    experience: 8,
    rating: 5,
    icon: IcSrcCode,
  },
  {
    id: Programming.HTML,
    title: t(Programming.HTML),
    experience: 8,
    rating: 5,
    icon: IcSrcCode,
  },
  {
    id: Programming.CSS,
    title: t(Programming.CSS),
    experience: 8,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Programming.SCSS,
    title: t(Programming.SCSS),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Programming.SQL,
    title: t(Programming.SQL),
    experience: 5,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Programming.Java,
    title: t(Programming.Java),
    experience: 8,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Programming.YAML,
    title: t(Programming.YAML),
    experience: 2,
    rating: 3,
    icon: IcSrcCode,
  },
];

export const ToolsSkills = (t: TFunction) => [
  {
    id: Tools.GithubCopilot,
    title: t(Tools.GithubCopilot),
    experience: 1.5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Tools.Claude,
    title: t(Tools.Claude),
    experience: 1.5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Tools.Vite,
    title: t(Tools.Vite),
    experience: 4,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Tools.ESBuild,
    title: t(Tools.ESBuild),
    experience: 1,
    rating: 2,
    icon: IcSrcCode,
  },
  {
    id: Tools.Webpack,
    title: t(Tools.Webpack),
    experience: 5,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Tools.Lighthouse,
    title: t(Tools.Lighthouse),
    experience: 4,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Tools.NewRelic,
    title: t(Tools.NewRelic),
    experience: 2,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Tools.Sentry,
    title: t(Tools.Sentry),
    experience: 2,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Tools.LogRocket,
    title: t(Tools.LogRocket),
    experience: 1,
    rating: 2,
    icon: IcSrcCode,
  },
  {
    id: Tools.WebpageTest,
    title: t(Tools.WebpageTest),
    experience: 3,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Tools.SonarQube,
    title: t(Tools.SonarQube),
    experience: 8,
    rating: 4,
    icon: IcSrcCode,
  },
];

export const DevopsSkills = (t: TFunction) => [
  {
    id: Devops.Git,
    title: t(Devops.Git),
    experience: 7,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Devops.Github,
    title: t(Devops.Github),
    experience: 7,
    rating: 5,
    icon: IcSrcCode,
  },
  {
    id: Devops.AzureDevops,
    title: t(Devops.AzureDevops),
    experience: 5,
    rating: 5,
    icon: IcSrcCode,
  },
  {
    id: Devops.BitBucket,
    title: t(Devops.BitBucket),
    experience: 3,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Devops.GithubActions,
    title: t(Devops.GithubActions),
    experience: 2,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Devops.Jenkins,
    title: t(Devops.Jenkins),
    experience: 8,
    rating: 2,
    icon: IcSrcCode,
  },
];

export const TestingSkills = (t: TFunction) => [
  {
    id: Testing.ReactTestingLibrary,
    title: t(Testing.ReactTestingLibrary),
    experience: 3,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Testing.Jest,
    title: t(Testing.Jest),
    experience: 7,
    rating: 4,
    icon: IcSrcCode,
  },
  {
    id: Testing.Vitest,
    title: t(Testing.Vitest),
    experience: 2,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Testing.Axe,
    title: t(Testing.Axe),
    experience: 3,
    rating: 3,
    icon: IcSrcCode,
  },
  {
    id: Testing.JUnit,
    title: t(Testing.JUnit),
    experience: 8,
    rating: 3,
    icon: IcSrcCode,
  },
];

export const AllSkills = (t: TFunction) => [
  ...ProgrammingSkills(t),
  ...FrontendSkills(t),
  ...BackendSkills(t),
  ...ToolsSkills(t),
  ...DevopsSkills(t),
  ...TestingSkills(t),
];
