import { Devops, Frontend, Programming, Testing, Tools } from "@base/enum";

// TODO: Remove dummy data after page completion
export const ExperienceData = [
  {
    role: "specialistSoftwareEngineer",
    company: "ltimindtree",
    startDate: "2024-10-15",
    endDate: "Present",
    duration: "1 Yr, 3 Ms",
    description: [
      "Designed & developed several key areas of 3 frontend apps from the ground up, establishing scalable patterns adopted across multiple teams.",
      "Architected AI-guided polymorphic modal system using Factory pattern, consolidating 4 modal variants into single reusable component through meta-prompting workflow, avoiding ~65% code redundancy.",
      "Optimized Dashboard performance by ~46%, reducing LCP from 4.89s to 2.23s and achieving 0 CLS through API integration and rendering improvements.",
      "Engineered seamless cross-application message passing functionality between the MFE and host apps.",
      "Led a team of 13 frontend and backend engineers to deliver high-quality features timely.",
      "Accelerated code reviews and eliminated manual PR verifications by establishing modular Copilot instruction files, enforcing coding standards, and ensuring predictable output.",
      "Contributed performant, reusable, decoupled, and maintainable components to strengthen the shared component library.",
    ],
    skills: [
      Frontend.React,
      Programming.Typescript,
      Tools.GithubCopilot,
      Tools.Claude,
      Frontend.RTKQuery,
      Frontend.Yup,
      Frontend.Axios,
      Frontend.I18N,
      Programming.SCSS,
      Frontend.MicroFrontend,
      Tools.Vite,
      Tools.Lighthouse,
      Testing.Vitest,
    ],
  },
  {
    role: "seniorSoftwareEngineer",
    company: "ltimindtree",
    startDate: "2021-05-24",
    endDate: "2024-10-15",
    duration: "3 Yr, 5 M ",
    description: [
      "Developed complex features and pixel-perfect, reusable UI components using React, Redux Toolkit, RTK Query, and SCSS.",
      "Seamlessly integrated frontend interfaces with backend REST APIs, ensuring seamless data flow and optimal user experience.",
      "Led cross-functional team of 10 developers, collaborating with Design, QA, Product, and Scrum teams to consistently deliver features every sprint.",
      "Drove ~20% productivity increase by boosting GitHub Copilot adoption through learning sessions on prompting (zero-shot, few-shot, context-driven) and leveraging Agentic development for systematic code generation.",
      "Mentored peers through complex problem-solving to ensure on-time delivery and foster a collaborative learning environment.",
    ],
    skills: [
      Frontend.React,
      Programming.Typescript,
      Frontend.RTKQuery,
      Tools.GithubCopilot,
      Frontend.Yup,
      Frontend.Axios,
      Frontend.I18N,
      Tools.Claude,
      Frontend.Formik,
      Frontend.ReduxSaga,
      Frontend.ReduxToolkit,
      Frontend.ReactRouter,
      Testing.ReactTestingLibrary,
      Testing.Axe,
    ],
  },
  {
    role: "softwareEngineer",
    company: "robertBosch",
    startDate: "2017-09-14",
    endDate: "2021-05-21",
    duration: "3 Yr, 8 M",
    description: [
      "Developed Signal Configuration editors and multi-widget Dashboard, enabling users to visualize complex configurations intuitively",
      "Built a custom domain-specific language editor allowing efficient signal header definition, reducing laborious configuration time programmatically.",
      "Implemented complex forms with custom regex validations, ensuring robust input accuracy and data integrity.",
      "Maintained 80%+ code coverage through comprehensive unit testing and enforced SonarQube quality gates.",
      "Created custom dependency analyzer and report generation tool, maintaining a clean architecture and reducing technical debt.",
      "Monitored and optimized Jenkins CI/CD pipelines, improving build reliability and deployment frequency",
    ],
    skills: [
      Programming.Java,
      Frontend.React,
      Programming.JavaScript,
      Frontend.ReduxSaga,
      Frontend.Axios,
      Frontend.Formik,
      Testing.JUnit,
      Devops.Git,
      Devops.BitBucket,
      Tools.SonarQube,
      Devops.Jenkins,
    ],
  },
];
