import {
  Rocket01Icon as IcRocket,
  CodeFolderIcon as IcCodeFolder,
  SourceCodeIcon as IcSrcCode,
  ReactIcon as IcReact,
  Globe02Icon as IcGlobe,
  CancelCircleIcon as IcCancel,
  Book02Icon as IcBook,
  Alert02Icon as IcAlert,
  Sent02Icon as IcSend,
  UserIcon as IcUser,
  Github01Icon as IcGithub,
  Linkedin01Icon as IcLinkedin,
  LeetcodeIcon as IcLeetcode,
  HackerrankIcon as IcHackerRank,
  ArrowLeft01Icon as IcChevronLeft,
  ArrowRight01Icon as IcChevronRight,
  LinkForwardIcon as IcLinkForward,
  CheckmarkCircle02Icon as IcCheckedCircle,
} from "@hugeicons/core-free-icons";

export {
  IcRocket,
  IcCodeFolder,
  IcSrcCode,
  IcReact,
  IcGlobe,
  IcCancel,
  IcBook,
  IcAlert,
  IcSend,
  IcUser,
  IcGithub,
  IcLinkedin,
  IcLeetcode,
  IcHackerRank,
  IcChevronLeft,
  IcChevronRight,
  IcLinkForward,
  IcCheckedCircle,
};
