import {
  Backend,
  Devops,
  Frontend,
  Programming,
  Testing,
  Tools,
} from "@base/enum";
import type { Project } from "@base/type";

export const Projects: Project[] = [
  {
    id: "rsyatra",
    title: "rsyatra",
    description: "rsyatra-desc",
    image: "/projects/rsyatra.png",
    liveUrl: "https://rsyatra.com",
    technologies: [
      Frontend.React,
      Frontend.RTKQuery,
      Tools.Claude,
      Tools.GithubCopilot,
      Programming.Typescript,
      Frontend.ReactHookForm,
      Frontend.RadixUI,
      Frontend.Zod,
    ],
  },
  {
    id: "autoposts-ai",
    title: "autoposts-ai",
    description: "autoposts-ai-desc",
    image: "/projects/autoposts-ai.png",
    githubUrl: "https://github.com/amitjoshi956/auto-posts-ai",
    liveUrl: "https://auto-posts-ai.web.app",
    technologies: [
      Frontend.React,
      Frontend.TanstackQuery,
      Tools.GithubCopilot,
      Backend.Node,
      Backend.Express,
      Backend.MongoDB,
      Backend.Firebase,
      Devops.GithubActions,
    ],
  },
  {
    id: "burger-builder",
    title: "burger-builder",
    description: "burger-builder-desc",
    image: "/projects/burger-builder.png",
    githubUrl: "https://github.com/amitjoshi956/burgerbuilder-app",
    liveUrl: "https://burger-builder-956.web.app/",
    technologies: [
      Frontend.React,
      Frontend.Axios,
      Programming.JavaScript,
      Backend.Firebase,
      Devops.Git,
      Devops.Github,
      Programming.HTML,
      Programming.CSS,
    ],
  },
  {
    id: "vidly",
    title: "vidly",
    description: "vidly-desc",
    image: "/projects/vidly.png",
    githubUrl: "https://github.com/amitjoshi956/vidly-app",
    technologies: [
      Programming.JavaScript,
      Backend.Node,
      Backend.Express,
      Backend.MongoDB,
      Backend.Mongoose,
      Testing.Jest,
    ],
  },
  {
    id: "soulflix",
    title: "soulflix",
    description: "soulflix-desc",
    image: "/projects/soulflix.png",
    liveUrl: "https://soulflix-app-108.web.app/",
    githubUrl: "https://github.com/amitjoshi956/soulflix-ui",
    technologies: [
      Frontend.React,
      Frontend.Axios,
      Tools.Claude,
      Programming.Typescript,
      Programming.SCSS,
      Backend.Firebase,
      Devops.GithubActions,
    ],
  },
];
